language: elixir

branches:
  only:
    - master

matrix:
  include:
    - otp_release: 19.0
      elixir: 1.3.4
    - otp_release: 19.3
      elixir: 1.4.2
    - otp_release: 20.0
      elixir: 1.5.3
    - otp_release: 21.0
      elixir: 1.6.6
    - otp_release: 21.0
      elixir: 1.7.3

sudo: false
